2020-01-23T02:29:49.808944+00:00 app[api]: Initial release by user tech.shpeuci@gmail.com
2020-01-23T02:29:49.808944+00:00 app[api]: Release v1 created by user tech.shpeuci@gmail.com
2020-01-23T02:29:50.112187+00:00 app[api]: Enable Logplex by user tech.shpeuci@gmail.com
2020-01-23T02:29:50.112187+00:00 app[api]: Release v2 created by user tech.shpeuci@gmail.com
2020-01-23T02:29:55.000000+00:00 app[api]: Build started by user tech.shpeuci@gmail.com
2020-01-23T02:30:22.468303+00:00 app[api]: Deploy f2172e69 by user tech.shpeuci@gmail.com
2020-01-23T02:30:22.468303+00:00 app[api]: Release v3 created by user tech.shpeuci@gmail.com
2020-01-23T02:30:30.000000+00:00 app[api]: Build succeeded
2020-01-23T02:30:33.991081+00:00 heroku[router]: at=error code=H14 desc="No web processes running" method=GET path="/" host=shpeportal.herokuapp.com request_id=6ef1545b-0a9c-47bd-8a09-5b685358e964 fwd="169.234.58.174" dyno= connect= service= status=503 bytes= protocol=https
2020-01-23T02:30:34.685999+00:00 heroku[router]: at=error code=H14 desc="No web processes running" method=GET path="/favicon.ico" host=shpeportal.herokuapp.com request_id=168d7340-8cf6-40cb-b838-dee5321c7370 fwd="169.234.58.174" dyno= connect= service= status=503 bytes= protocol=https
2020-01-23T04:57:20.000000+00:00 app[api]: Build started by user tech.shpeuci@gmail.com
2020-01-23T04:57:48.287125+00:00 app[api]: Deploy 62b37110 by user tech.shpeuci@gmail.com
2020-01-23T04:57:48.287125+00:00 app[api]: Release v4 created by user tech.shpeuci@gmail.com
2020-01-23T04:57:48.302066+00:00 app[api]: Scaled to web@1:Free by user tech.shpeuci@gmail.com
2020-01-23T04:57:51.632609+00:00 heroku[web.1]: Starting process with command `gunicorn flaskr:__init__`
2020-01-23T04:57:53.322602+00:00 heroku[web.1]: State changed from starting to up
2020-01-23T04:57:53.647724+00:00 heroku[web.1]: State changed from up to crashed
2020-01-23T04:57:53.652326+00:00 heroku[web.1]: State changed from crashed to starting
2020-01-23T04:57:53.493560+00:00 app[web.1]: [2020-01-23 04:57:53 +0000] [4] [INFO] Shutting down: Master
2020-01-23T04:57:53.493750+00:00 app[web.1]: [2020-01-23 04:57:53 +0000] [4] [INFO] Reason: App failed to load.
2020-01-23T04:57:53.199877+00:00 app[web.1]: [2020-01-23 04:57:53 +0000] [4] [INFO] Starting gunicorn 19.9.0
2020-01-23T04:57:53.200427+00:00 app[web.1]: [2020-01-23 04:57:53 +0000] [4] [INFO] Listening at: http://0.0.0.0:12199 (4)
2020-01-23T04:57:53.200520+00:00 app[web.1]: [2020-01-23 04:57:53 +0000] [4] [INFO] Using worker: sync
2020-01-23T04:57:53.204277+00:00 app[web.1]: [2020-01-23 04:57:53 +0000] [10] [INFO] Booting worker with pid: 10
2020-01-23T04:57:53.235143+00:00 app[web.1]: [2020-01-23 04:57:53 +0000] [11] [INFO] Booting worker with pid: 11
2020-01-23T04:57:53.349336+00:00 app[web.1]: Failed to find application object '__init__' in 'flaskr'
2020-01-23T04:57:53.349896+00:00 app[web.1]: [2020-01-23 04:57:53 +0000] [10] [INFO] Worker exiting (pid: 10)
2020-01-23T04:57:53.374636+00:00 app[web.1]: Failed to find application object '__init__' in 'flaskr'
2020-01-23T04:57:53.375162+00:00 app[web.1]: [2020-01-23 04:57:53 +0000] [11] [INFO] Worker exiting (pid: 11)
2020-01-23T04:57:53.630711+00:00 heroku[web.1]: Process exited with status 4
2020-01-23T04:57:56.000000+00:00 app[api]: Build succeeded
2020-01-23T04:57:56.339858+00:00 heroku[web.1]: Starting process with command `gunicorn flaskr:__init__`
2020-01-23T04:57:59.107559+00:00 app[web.1]: [2020-01-23 04:57:59 +0000] [4] [INFO] Starting gunicorn 19.9.0
2020-01-23T04:57:59.108139+00:00 app[web.1]: [2020-01-23 04:57:59 +0000] [4] [INFO] Listening at: http://0.0.0.0:22950 (4)
2020-01-23T04:57:59.108262+00:00 app[web.1]: [2020-01-23 04:57:59 +0000] [4] [INFO] Using worker: sync
2020-01-23T04:57:59.112629+00:00 app[web.1]: [2020-01-23 04:57:59 +0000] [10] [INFO] Booting worker with pid: 10
2020-01-23T04:57:59.191237+00:00 app[web.1]: [2020-01-23 04:57:59 +0000] [11] [INFO] Booting worker with pid: 11
2020-01-23T04:57:59.261092+00:00 app[web.1]: Failed to find application object '__init__' in 'flaskr'
2020-01-23T04:57:59.261737+00:00 app[web.1]: [2020-01-23 04:57:59 +0000] [10] [INFO] Worker exiting (pid: 10)
2020-01-23T04:57:59.350527+00:00 app[web.1]: Failed to find application object '__init__' in 'flaskr'
2020-01-23T04:57:59.351020+00:00 app[web.1]: [2020-01-23 04:57:59 +0000] [11] [INFO] Worker exiting (pid: 11)
2020-01-23T04:57:59.395800+00:00 app[web.1]: Traceback (most recent call last):
2020-01-23T04:57:59.395819+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.6/site-packages/gunicorn/arbiter.py", line 210, in run
2020-01-23T04:57:59.396189+00:00 app[web.1]: self.sleep()
2020-01-23T04:57:59.396198+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.6/site-packages/gunicorn/arbiter.py", line 360, in sleep
2020-01-23T04:57:59.396528+00:00 app[web.1]: ready = select.select([self.PIPE[0]], [], [], 1.0)
2020-01-23T04:57:59.396535+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.6/site-packages/gunicorn/arbiter.py", line 245, in handle_chld
2020-01-23T04:57:59.396743+00:00 app[web.1]: self.reap_workers()
2020-01-23T04:57:59.396749+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.6/site-packages/gunicorn/arbiter.py", line 528, in reap_workers
2020-01-23T04:57:59.396995+00:00 app[web.1]: raise HaltServer(reason, self.APP_LOAD_ERROR)
2020-01-23T04:57:59.397041+00:00 app[web.1]: gunicorn.errors.HaltServer: <HaltServer 'App failed to load.' 4>
2020-01-23T04:57:59.397048+00:00 app[web.1]: 
2020-01-23T04:57:59.397050+00:00 app[web.1]: During handling of the above exception, another exception occurred:
2020-01-23T04:57:59.397052+00:00 app[web.1]: 
2020-01-23T04:57:59.397057+00:00 app[web.1]: Traceback (most recent call last):
2020-01-23T04:57:59.397061+00:00 app[web.1]: File "/app/.heroku/python/bin/gunicorn", line 11, in <module>
2020-01-23T04:57:59.397193+00:00 app[web.1]: sys.exit(run())
2020-01-23T04:57:59.397199+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.6/site-packages/gunicorn/app/wsgiapp.py", line 61, in run
2020-01-23T04:57:59.397343+00:00 app[web.1]: WSGIApplication("%(prog)s [OPTIONS] [APP_MODULE]").run()
2020-01-23T04:57:59.397349+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.6/site-packages/gunicorn/app/base.py", line 223, in run
2020-01-23T04:57:59.397523+00:00 app[web.1]: super(Application, self).run()
2020-01-23T04:57:59.397529+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.6/site-packages/gunicorn/app/base.py", line 72, in run
2020-01-23T04:57:59.397708+00:00 app[web.1]: Arbiter(self).run()
2020-01-23T04:57:59.397714+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.6/site-packages/gunicorn/arbiter.py", line 232, in run
2020-01-23T04:57:59.397876+00:00 app[web.1]: self.halt(reason=inst.reason, exit_status=inst.exit_status)
2020-01-23T04:57:59.397882+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.6/site-packages/gunicorn/arbiter.py", line 345, in halt
2020-01-23T04:57:59.398121+00:00 app[web.1]: self.stop()
2020-01-23T04:57:59.398128+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.6/site-packages/gunicorn/arbiter.py", line 393, in stop
2020-01-23T04:57:59.398430+00:00 app[web.1]: time.sleep(0.1)
2020-01-23T04:57:59.398436+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.6/site-packages/gunicorn/arbiter.py", line 245, in handle_chld
2020-01-23T04:57:59.398602+00:00 app[web.1]: self.reap_workers()
2020-01-23T04:57:59.398608+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.6/site-packages/gunicorn/arbiter.py", line 528, in reap_workers
2020-01-23T04:57:59.398847+00:00 app[web.1]: raise HaltServer(reason, self.APP_LOAD_ERROR)
2020-01-23T04:57:59.398876+00:00 app[web.1]: gunicorn.errors.HaltServer: <HaltServer 'App failed to load.' 4>
2020-01-23T04:57:59.557621+00:00 heroku[web.1]: State changed from starting to crashed
2020-01-23T04:57:59.540304+00:00 heroku[web.1]: Process exited with status 1
2020-01-23T04:58:06.715141+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/" host=shpeportal.herokuapp.com request_id=7115ff9b-9064-41c3-97a6-22e556bfa0e8 fwd="169.234.58.174" dyno= connect= service= status=503 bytes= protocol=https
2020-01-23T04:58:06.862643+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/robots.txt" host=shpeportal.herokuapp.com request_id=e9633172-6c35-4022-b801-7f34319f42e5 fwd="169.234.58.174" dyno= connect= service= status=503 bytes= protocol=https
2020-01-23T04:58:07.661102+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/favicon.ico" host=shpeportal.herokuapp.com request_id=49227e39-9182-4f4d-aa75-c11df238574a fwd="169.234.58.174" dyno= connect= service= status=503 bytes= protocol=https
